backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

logo_url: https://meaningfulnonsense.ca/icons/icon-512x512.png

site_url: https://meaningfulnonsense.ca

media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog Post'
    folder: 'src/pages/blog'
    create: true
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    preview_path: 'blog/{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Label', name: 'label', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', dateFormat: true }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Author’s Note', name: 'authorNote', widget: 'authorNote', required: false }
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Stories', value: 'stories' }
          - { label: 'Serendipity', value: 'serendipity' }
          - { label: 'Life', value: 'life' }
          - { label: 'Everyday Thoughts', value: 'everyday-thoughts' }
          - { label: 'Life Lessons', value: 'life-lessons' }

  - name: 'pages'
    label: 'Page'
    files:
      - file: 'src/pages/photography/index.md'
        label: 'Photography'
        name: 'photography'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'photography' }
          - {
              label: 'Photographs',
              name: 'photos',
              widget: 'list',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Date', name: 'date', widget: 'date', format: 'DD/MM/YY' },
                  { label: 'Location', name: 'location', widget: string },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
